language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
script: > 
          cmake external/source/glfw && make && make install
          &&
          ./autogen.sh && ./configure && make && make install
          &&
          $CXX -std=c++0x -Wall
          -O3 -s -fno-exceptions -fno-rtti 
          -DGLEW_STATIC
          -Iexternal/
          -lglfw3
          -luv
          external/source/glew.cpp
          polymania/*.cpp
          polymania/other/*.cpp
before_install: >
                  sudo apt-get update -qq
                  &&
                  sudo apt-get install 
                  cmake 
                  libxxf86vm-dev 
                  x11proto-xf86vidmode-dev 
  