language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
script: > 
          pushd external/source/glfw && mkdir build && cd build && cmake .. && make -j && sudo make install && popd
          &&
          pushd external/source/libuv && ./autogen.sh && ./configure && make -j && sudo make install && popd
          &&
          echo "BUILDING POLYMANIA" 
          && 
          $CXX -std=c++0x -Wall -Wextra -pedantic -Wno-unused-parameter
          -O3 -s -fno-exceptions -fno-rtti -static-libstdc++ -static-libgcc
          -DGLM_FORCE_CXX03
          -DGLEW_STATIC
          -Iexternal/
          external/source/glew.cpp
          polymania/*.cpp
          polymania/other/*.cpp
          -Wl,-Bstatic
          -luv
          -lglfw3
          -lXrandr
          -lXrender
          -lXxf86vm
          -lXext
          -lX11
          -lXi
          -Wl,-Bdynamic
          -lGL
          -pthread
          -Wl,--as-needed
          &&
          echo "FINISHED BUILDING POLYMANIA" 
          &&          
          ls -lh && ldd a.out && echo "ITS DONE!"
before_install: >
                  sudo apt-get update -qq
                  &&
                  sudo apt-get install 
                  cmake 
                  libxxf86vm-dev 
                  x11proto-xf86vidmode-dev 
                  libxrandr-dev
