language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
script: $CXX -std=c++0x -O3 -static -flto -fno-exceptions -fno-rtti -DGLEW_STATIC -Iexternal/ external/source/glew.cpp polymania/*.cpp
